### ISSUE TITLE
想學 grep awk sed  

### ISSUE THREAD

**Issue by jawayang** [softnshare/devtools#14]
想學 grep awk sed 但是卻不知道怎麼入門
雖然會寫一點 js 的正規表示式
但是 grep awk sed 的正規表示式，完全不是這樣一回事
不知道該怎麼入門
請教大大們有沒有什麼方式可以學好基礎？

**Comment by metavige** [comment]
我都是到這邊來看資料的～
鳥哥的 Linux 私房菜 - http://linux.vbird.org/

**Comment by jawayang** [comment]
@metavige  謝謝。
我有上去看過，不過他的UX與UI介面實在是太可怕了～ XD
資料很多，but 還是看不懂~

**Comment by jawayang** [comment]
好吧～
我找了一個工具把他的UI改良一下
https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb

``` css
* {
      line-height: 1.6em;
      font-family: -webkit-body;
}
pre,pre *,span{
      font-family: monospace !important;
      padding:10p !important;
      line-height: 1.6em !important;
}
```

改良前與改良後
![afternbefore](https://cloud.githubusercontent.com/assets/8079787/16185811/03910a26-36f9-11e6-84f5-2534dec0ab63.png)
